namespace: open-cluster-management

resources:
- addon/clustermanagementaddon.yaml
- addon/rbac.yaml
- addon/controller.yaml

images:
- name: example-addon-image
  newName: quay.io/open-cluster-management/addons
  newTag: latest

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
