kind: Deployment
apiVersion: apps/v1
metadata:
  name: helm-addon-controller
  labels:
    app: helm-addon-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-addon-controller
  template:
    metadata:
      labels:
        app: helm-addon-controller
    spec:
      serviceAccountName: helm-addon-sa
      containers:
      - name: helm-addon-controller
        image: quay.io/open-cluster-management/addons:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/helm-addon"
