kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leaseprober-addon-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leaseprober-addon-agent
subjects:
  - kind: ServiceAccount
    name: leaseprober-addon-agent-sa
    namespace: open-cluster-management-agent-addon
