kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leaseprober-addon-agent
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
   