kind: Deployment
apiVersion: apps/v1
metadata:
  name: leaseprober-addon-agent
  namespace: open-cluster-management-agent-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      addon: busybox
  template:
    metadata:
      labels:
        addon: busybox
    spec:
      serviceAccountName: leaseprober-addon-agent-sa
      containers:
      - name: leaseprober-addon-agent
        image: quay.io/open-cluster-management/addons:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/leaseprober-agent"
