kind: Deployment
apiVersion: apps/v1
metadata:
  name: leaseprober-addon-controller
  labels:
    app: leaseprober-addon-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaseprober-addon-controller
  template:
    metadata:
      labels:
        app: leaseprober-addon-controller
    spec:
      serviceAccountName: leaseprober-addon-sa
      containers:
      - name: leaseprober-addon-controller
        image: quay.io/open-cluster-management/addons:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/leaseprober-addon"
